### ISSUE TITLE
Add API documentation using Swagger

### ISSUE THREAD

**Issue by Zaid-Safadi** [Zaid-Safadi/DICOMcloud#12]

**Comment by Zaid-Safadi** [comment]
added in b3cb8ae272791a2178725ca6838760dbd5c8d516

**Comment by yjsyyyjszf** [comment]
Can you help me ? for example  how to setup and test?  how to apprehend relations of  DICOMCloud and dicom-webJS ?

**Comment by yjsyyyjszf** [comment]
Can you help me ? how to dicom-webJS  refer DICOMCloud？

**Comment by Zaid-Safadi** [comment]
@yjsyyyjszf , the documentation here [https://github.com/Zaid-Safadi/DICOMcloud/wiki/Building-and-Running-the-code](https://github.com/Zaid-Safadi/DICOMcloud/wiki/Building-and-Running-the-code) has detailed instruction for running the server. 
To connect with dicom-webjs, just update the value of the "app:serverUrl" in the appSettings section of the [web.config](https://github.com/Zaid-Safadi/dicom-webJS/blob/master/Demo/Web.config)

Please open a new issue if you have any further questions and I'll be happy to help.
