### ISSUE TITLE
Discuss adaptation requirements  with "fo-dicom" 

### ISSUE THREAD

**Issue by Zaid-Safadi** [Zaid-Safadi/DICOMcloud#2]
This is an issue to discuss what are the fo-dicom prerequisites for adaptation.
- target .NET Framework PCL profile 111 as much as possible 

what is the followed standard? links?

**Comment by Zaid-Safadi** [comment]
I created a new branch "fo-dicom-integration" that compiles with fo-dicom successfully and removed ClearCanvas.

There are still issues that need to be fixed when running the code.

Main thing I noticed is working with elements in fo-dicom is not as easy as I like. Creating elements, updating values...
Also, I was hoping ChangeTransferSyntax will do all the magic but seems it doesn't work from Any-to-Any. This should be updated to support that.

@anders9ustafsson any thoughts?

**Comment by anders9ustafsson** [comment]
@Zaid-Safadi I am not sure I understand the transfer syntax comment? What are you trying to do and in what way doesn't it work? Please note that `ChangeTransferSyntax` is a little bit of a misnomer; it doesn't change the transfer syntax of the existing object, but it creates a new object with the requested syntax.

Regarding `DicomElement` API, what would you like to see? Again, I realize it could be confusing, but the `Add` method is actually doing _replace-or-add_. But maybe there is something else you are missing?

I heartily admit that there are quite a few API legacies in _fo-dicom_. For backwards compatibility we have been reluctant renaming methods, but of course we continuously need to re-evaluate those standpoints. If you have renaming suggestions, don't hesitate to post them on _fo-dicom_'s issue board.

**Comment by Zaid-Safadi** [comment]
@anders9ustafsson, I am taking a closer look at the library and now I better understand the interfaces and APIs, so far so good!

Regarding the ChangeTransferSyntax, here is what I am trying to do . I have a J2K 16-bit allocated/12-bits stored image that I want to change to Jpeg. I started with converting to Jpeg Lossy Process 1 but that failed because it requires the original image to be 8-bit (is this a hard requirement or limitation?)

Then tried the same image with "DICOM Dump" tool to change the transfer to JPEG lossy process 4 but received an exception:
 Unable to cast object of type 'Dicom.Imaging.Codec.DicomJpegParams' to type 'Dicom.Imaging.Codec.DicomJpeg2000Params'.

As for the DicomElement, I guess I figured out mostly how it works except of how to append an element value multiplicity. Seems I have to always set the value in the constructor as I can't find a way to insert a value at an index. e.g. element.Set<string>("myValue", 1)

If you can confirm that these are legitimate issues then I can post them into the do-dicom issue board

> You can download the file using this link (might timeout first request):
> [https://dicomcloud.azurewebsites.net/api/wadouri?RequestType=wado&studyUID=1.2.840.113745.101000.1008000.38046.4274.5925160&seriesUID=1.3.12.2.1107.5.2.5.11090.2.0.1502761120021701&objectUID=1.3.12.2.1107.5.2.5.11090.5.0.5823652214913032&contentType=application/dicom](https://dicomcloud.azurewebsites.net/api/wadouri?RequestType=wado&studyUID=1.2.840.113745.101000.1008000.38046.4274.5925160&seriesUID=1.3.12.2.1107.5.2.5.11090.2.0.1502761120021701&objectUID=1.3.12.2.1107.5.2.5.11090.5.0.5823652214913032&contentType=application/dicom)

**Comment by anders9ustafsson** [comment]
@Zaid-Safadi Problem 2, in DICOM Dump, definitely sounds like a real issue, so please feel free to report it.

Regarding problem 1, I need to double-check, but I think that the transfer syntax operations do not support downsampling to fewer bits. I'll get back to you on this issue.

Regarding problem 3, a very good suggestion! Please feel free to add this feature request to the issue board as well.

BTW, very convenient file download :-)

**Comment by Zaid-Safadi** [comment]
@anders9ustafsson, I completed a successful integration with fo-dicom replacing ClearCanvas dependencies and supporting a two way (JSON/XML <--> DicomDataset) conversion with bulk-data and inline binary.

There are minor stuff that I still need to look at but the results and testing so far seems good . I have both implementation hosted and you can see the output XML [in the live demo](http://dicomweb.azurewebsites.net/) (binary data stripped)

I didn't do a conclusive test but I am able to load the codec (Dicom.Native) dll and use it to uncompress the different transfer syntaxes i'm  throwing at it, which is very exciting!

Let me know if you have any thoughts

Here is an example to convert To/From XML: 
https://gist.github.com/Zaid-Safadi/91a404890a2c9f3a869ce79ed5c3adfb

**Comment by anders9ustafsson** [comment]
Great stuff, @Zaid-Safadi ! Feel free to promote this project in the _fo-dicom_ chat room on Gitter, I am sure that it is of great interest to many _fo-dicom_ users.

One question: you have implemented your own JSON converter. Is there anything in _fo-dicom_'s own JSON converter that you find limiting?

Ideally, I would like to see both JSON and XML support confined to the _fo-dicom_ core packages. Would you be interested and willing to contribute the XML implementation to _fo-dicom_?

**Comment by Zaid-Safadi** [comment]
@anders9ustafsson I had the JSON converter implemented in the older code so it made sense for me to just update it with the rest and have a consistent implementation for both converters with the added functionalities to the DicomDataset.

I'm planning to redesign and consolidate some of the projects to simplify the user experience, this will also include moving some of the code to the DICOM toolkit - fo-dicom :) 

on a separate note, may I ask what is the reason for having the JSON converter in fo-dicom as a separate project? Are you thinking that the XML converter should also be in its own project?

**Comment by anders9ustafsson** [comment]
@Zaid-Safadi This sounds good, looking forward to your upcoming contributions :-)

The reason why the _fo-dicom_ JSON converter is in a separate project and package, is because it has a dependency to _JSON.Net_. We did not want to make _fo-dicom_ dependent on other NuGet packages just because of this isolated functionality, so therefore we created a separate package for it instead.

**Comment by anders9ustafsson** [comment]
Provided the XML converter has no external (NuGet) dependencies, it can perfectly well be included in the core files, provided that the associated classes can build on all platforms, including PCL Profile 111. 

I have not checked the XML converter code in detail, but if it is .NET Framework specific, you would also in that case need to prepare a separate .NET targeting project and package.

**Comment by Zaid-Safadi** [comment]
I'll close this for now and we'll keep an eye on opportunities of integration
